steps:
- id: cache-gcloud
  waitFor:
  - '-'
  name: gcr.io/cloud-builders/docker
  args:
  - pull
  - gcr.io/google.com/cloudsdktool/cloud-sdk
- id: build
  waitFor:
  - '-'
  name: gcr.io/cloud-builders/docker
  timeout: 3600s
  args:
  - build
  - -f=Dockerfile.base
  - --tag=us-docker.pkg.dev/${PROJECT_ID}/container-images/ql_discourse-base:commit-${COMMIT_SHA}
  - .
- id: push
  waitFor:
  - build
  name: gcr.io/cloud-builders/docker
  args:
  - push
  - us-docker.pkg.dev/${PROJECT_ID}/container-images/ql_discourse-base:commit-${COMMIT_SHA}

timeout: 3600s
images:
- us-docker.pkg.dev/${PROJECT_ID}/container-images/ql_discourse-base:commit-${COMMIT_SHA}
